"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Caden Wonzer and Isabella Chojnacki, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: czw99
UT EID 2: ilc422
"""


def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if group_sum(start+1, nums, target-nums[start]):
        return True
    if group_sum(start+1, nums, target):
        return True
    return False


def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if nums[start] == 6:
        return group_sum_6(start+1, nums, target-6)
    if group_sum_6(start+1, nums, target-nums[start]):
        return True
    if group_sum_6(start+1, nums, target):
        return True
    return False


def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if group_no_adj(start+2, nums, target-nums[start]):
        return True
    if group_no_adj(start+1, nums, target):
        return True
    return False

def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if nums[start] % 5 == 0 and start+1 < len(nums):
        if nums[start+1] == 1:
            return group_sum_5(start+2, nums, target)
        else:
            return group_sum_5(start+1, nums, target-nums[start])
    if group_sum_5(start+1, nums, target-nums[start]):
        return group_sum_5(start+1, nums, target-nums[start])
    if group_sum_5(start+1, nums, target):
        return True
    return False

def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    GroupSum = nums[start]
    NextIndex = start + 1
    while NextIndex < len(nums) and nums[NextIndex] == nums[start]:
        GroupSum += nums[NextIndex]
        NextIndex += 1
    if group_sum_clump(NextIndex, nums, target - GroupSum):
        return True
    if group_sum_clump(NextIndex, nums, target):
        return True
    return False

def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    def helper(index, target):
        if target == 0:
            return True
        if index == len(nums) or target < 0:
            return False
        include = helper(index + 1, target - nums[index])
        exclude = helper(index + 1, target)
        return include or exclude
    total = sum(nums)
    if total % 2 != 0:
        return False
    return helper(0, total //2)


def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    def helper(index, OddSum, DivSum):
        if index == len(nums):
            return OddSum % 2 == 1 and DivSum % 10 == 0
        InOddSum = helper(index + 1, OddSum + nums[index], DivSum)
        InDivSum = helper(index + 1, OddSum, DivSum + nums[index])
        return InOddSum or InDivSum
    return helper(0, 0, 0)


def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    if len(nums) == 0:
        return False
    
    def helper(index, Group1Sum, Group2Sum):
        if index == len(nums):
            return Group1Sum == Group2Sum
        if nums[index] % 5 == 0:
            return helper(index + 1, Group1Sum + nums[index], Group2Sum)
        elif nums[index] % 3 == 0:
            return helper(index + 1, Group1Sum, Group2Sum + nums[index])
        else:
            InGroup1 = helper(index + 1, Group1Sum + nums[index], Group2Sum)
            InGroup2 = helper(index + 1, Group1Sum, Group2Sum + nums[index])
            return InGroup1 or InGroup2
    return helper(0, 0, 0)
